from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

STRUCTURED_RELAY_DATASETS = (
    "adj_factor",
    "moneyflow",
    "ths_index",
    "ths_member",
    "block_moneyflow",
    "stk_auction_replay",
)

INSTITUTION_RELAY_DATASETS = (
    "moneyflow_hsgt",
    "hk_hold",
    "fund_portfolio",
)

FINANCIAL_STATEMENT_RELAY_DATASETS = (
    "income",
    "balancesheet",
    "cashflow",
)

ANALYST_RELAY_DATASETS = (
    "report_rc",
    "analyst_rank",
    "analyst_detail",
    "analyst_history",
)

TEXT_RELAY_DATASETS = (
    "anns_d",
    "stock_zh_a_disclosure_report_cninfo",
    "stock_research_report_em",
    "news_cctv",
    "news_economic_baidu",
    "major_news",
)


@dataclass(frozen=True)
class RelayDatasetSpec:
    name: str
    display_name: str
    api_name: str
    storage_dataset: str
    date_col: str
    category: str
    description: str
    recommended_frequency: str
    risk_level: str
    requires_qmt: bool = False
    requires_relay_key: bool = True
    symbol_scoped: bool = False
    date_scoped: bool = True
    default_enabled: bool = False
    text_source: bool = False
    default_params: dict[str, Any] = field(default_factory=dict)


RELAY_DATASET_SPECS: dict[str, RelayDatasetSpec] = {
    "adj_factor": RelayDatasetSpec(
        name="adj_factor",
        display_name="复权因子",
        api_name="adj_factor",
        storage_dataset="adj_factors",
        date_col="trade_date",
        category="relay_structured",
        description="A 股复权因子，作为价格复权和收益校验的基础数据。",
        recommended_frequency="daily",
        risk_level="low",
        symbol_scoped=True,
        default_enabled=True,
    ),
    "moneyflow": RelayDatasetSpec(
        name="moneyflow",
        display_name="个股资金流",
        api_name="moneyflow",
        storage_dataset="moneyflow",
        date_col="trade_date",
        category="relay_structured",
        description="按大小单拆分的个股资金流，可派生净流入金额和净流入量。",
        recommended_frequency="daily",
        risk_level="medium",
        symbol_scoped=True,
        default_enabled=True,
    ),
    "ths_index": RelayDatasetSpec(
        name="ths_index",
        display_name="同花顺板块字典",
        api_name="ths_index",
        storage_dataset="ths_index",
        date_col="snapshot_date",
        category="relay_structured",
        description="同花顺行业、概念等板块字典，按快照日期留存。",
        recommended_frequency="weekly",
        risk_level="medium",
        date_scoped=False,
        default_enabled=True,
        default_params={"exchange": "A", "type": "N", "limit": 1000},
    ),
    "ths_member": RelayDatasetSpec(
        name="ths_member",
        display_name="同花顺板块成分",
        api_name="ths_member",
        storage_dataset="ths_member",
        date_col="snapshot_date",
        category="relay_structured",
        description="同花顺板块成分，用于板块暴露和主题池分析。",
        recommended_frequency="weekly",
        risk_level="medium",
        date_scoped=False,
        default_enabled=True,
        default_params={"limit": 1000, "ths_member_limit": 50},
    ),
    "block_moneyflow": RelayDatasetSpec(
        name="block_moneyflow",
        display_name="板块资金流",
        api_name="block_moneyflow",
        storage_dataset="block_moneyflow",
        date_col="trade_date",
        category="relay_structured",
        description="板块维度资金流，当前接口大 limit 不稳定，默认小批量采集。",
        recommended_frequency="daily",
        risk_level="medium",
        default_enabled=True,
        default_params={"limit": 5},
    ),
    "stk_auction_replay": RelayDatasetSpec(
        name="stk_auction_replay",
        display_name="集合竞价回放",
        api_name="stk_auction_replay",
        storage_dataset="auction_replay",
        date_col="datetime",
        category="relay_structured",
        description="09:15-09:30 集合竞价摘要或序列，独立于普通分钟 K 落库。",
        recommended_frequency="daily",
        risk_level="medium",
        symbol_scoped=True,
        default_enabled=True,
        default_params={"mode": "summary"},
    ),
    "moneyflow_hsgt": RelayDatasetSpec(
        name="moneyflow_hsgt",
        display_name="沪深港通资金流",
        api_name="moneyflow_hsgt",
        storage_dataset="hsgt_moneyflow",
        date_col="trade_date",
        category="relay_institution",
        description="沪深港通北向/南向聚合资金流，只适合做市场状态或风格 regime，不是个股截面持仓。",
        recommended_frequency="daily",
        risk_level="medium",
        default_enabled=False,
        default_params={
            "fields": "trade_date,ggt_ss,ggt_sz,hgt,sgt,north_money,south_money",
        },
    ),
    "hk_hold": RelayDatasetSpec(
        name="hk_hold",
        display_name="沪深港通持股",
        api_name="hk_hold",
        storage_dataset="hsgt_holdings",
        date_col="trade_date",
        category="relay_institution",
        description="沪股通/深股通个股持股明细，可用于北向持股比例、连续增持和拥挤度变化。",
        recommended_frequency="weekly",
        risk_level="high",
        default_enabled=False,
        default_params={
            "exchanges": ["SH", "SZ"],
            "limit": 3800,
            "fields": "trade_date,ts_code,name,vol,ratio,exchange",
        },
    ),
    "fund_portfolio": RelayDatasetSpec(
        name="fund_portfolio",
        display_name="基金股票持仓",
        api_name="fund_portfolio",
        storage_dataset="fund_portfolio_holdings",
        date_col="end_date",
        category="relay_institution",
        description="公募基金季度股票持仓，支持按基金、股票或报告期同步，用于基金持仓超配与抱团降温。",
        recommended_frequency="quarterly",
        risk_level="high",
        default_enabled=False,
        default_params={
            "limit": 5000,
            "period_limit": 8,
            "fields": "ts_code,ann_date,end_date,symbol,mkv,amount,stk_mkv_ratio,stk_float_ratio",
        },
    ),
    "income": RelayDatasetSpec(
        name="income",
        display_name="利润表",
        api_name="income",
        storage_dataset="financial_income",
        date_col="f_ann_date",
        category="relay_financial_statement",
        description="Tushare 利润表，按实际公告日落库，补充研发费用、收入、利润等三表字段。",
        recommended_frequency="weekly",
        risk_level="medium",
        symbol_scoped=True,
        default_enabled=False,
        default_params={
            "limit": 5000,
            "fields": "ts_code,ann_date,f_ann_date,end_date,report_type,comp_type,end_type,total_revenue,revenue,total_cogs,oper_cost,sell_exp,admin_exp,fin_exp,rd_exp,operate_profit,total_profit,n_income,n_income_attr_p,ebit,ebitda,update_flag",
        },
    ),
    "balancesheet": RelayDatasetSpec(
        name="balancesheet",
        display_name="资产负债表",
        api_name="balancesheet",
        storage_dataset="financial_balancesheet",
        date_col="f_ann_date",
        category="relay_financial_statement",
        description="Tushare 资产负债表，补充无形资产、商誉、研发资本化、资产负债与股东权益字段。",
        recommended_frequency="weekly",
        risk_level="medium",
        symbol_scoped=True,
        default_enabled=False,
        default_params={
            "limit": 5000,
            "fields": "ts_code,ann_date,f_ann_date,end_date,report_type,comp_type,end_type,total_assets,total_liab,total_hldr_eqy_exc_min_int,total_hldr_eqy_inc_min_int,intan_assets,r_and_d,goodwill,total_cur_assets,total_nca,total_cur_liab,total_ncl,update_flag",
        },
    ),
    "cashflow": RelayDatasetSpec(
        name="cashflow",
        display_name="现金流量表",
        api_name="cashflow",
        storage_dataset="financial_cashflow",
        date_col="f_ann_date",
        category="relay_financial_statement",
        description="Tushare 现金流量表，补充经营现金流、资本开支与自由现金流字段。",
        recommended_frequency="weekly",
        risk_level="medium",
        symbol_scoped=True,
        default_enabled=False,
        default_params={
            "limit": 5000,
            "fields": "ts_code,ann_date,f_ann_date,end_date,report_type,comp_type,end_type,net_profit,n_cashflow_act,im_net_cashflow_oper_act,c_pay_acq_const_fiolta,n_cashflow_inv_act,free_cashflow,amort_intang_assets,depr_fa_coga_dpba,stot_out_inv_act,update_flag",
        },
    ),
    "report_rc": RelayDatasetSpec(
        name="report_rc",
        display_name="卖方盈利预测",
        api_name="report_rc",
        storage_dataset="analyst_report_forecasts",
        date_col="report_date",
        category="relay_analyst",
        description="Tushare 卖方研报盈利预测，包含 EPS、净利润、估值、评级和目标价字段；适合离线慢同步。",
        recommended_frequency="daily",
        risk_level="high",
        symbol_scoped=True,
        default_enabled=False,
        default_params={"limit": 100},
    ),
    "analyst_rank": RelayDatasetSpec(
        name="analyst_rank",
        display_name="分析师排名",
        api_name="analyst_rank",
        storage_dataset="analyst_rank",
        date_col="update_date",
        category="relay_analyst",
        description="分析师年度排名、行业和 12 个月收益率，用于给研报预测或跟踪事件做质量加权。",
        recommended_frequency="monthly",
        risk_level="medium",
        date_scoped=False,
        default_enabled=False,
        default_params={"limit": 50},
    ),
    "analyst_detail": RelayDatasetSpec(
        name="analyst_detail",
        display_name="分析师当前跟踪",
        api_name="analyst_detail",
        storage_dataset="analyst_detail",
        date_col="latest_rating_date",
        category="relay_analyst",
        description="按 analyst_id 下钻的当前跟踪成分股、最新评级和阶段涨跌幅；会先从 analyst_rank 取 analyst_id。",
        recommended_frequency="weekly",
        risk_level="high",
        date_scoped=False,
        default_enabled=False,
        default_params={"indicator": "最新跟踪成分股", "limit": 50, "analyst_limit": 50},
    ),
    "analyst_history": RelayDatasetSpec(
        name="analyst_history",
        display_name="分析师历史跟踪",
        api_name="analyst_history",
        storage_dataset="analyst_history",
        date_col="in_date",
        category="relay_analyst",
        description="按 analyst_id 下钻的历史跟踪股票、调入调出日期、调出原因和累计涨跌幅。",
        recommended_frequency="monthly",
        risk_level="high",
        date_scoped=False,
        default_enabled=False,
        default_params={"indicator": "历史跟踪成分股", "limit": 100, "analyst_limit": 50},
    ),
    "anns_d": RelayDatasetSpec(
        name="anns_d",
        display_name="Tushare 公告",
        api_name="anns_d",
        storage_dataset="announcements",
        date_col="ann_date",
        category="relay_text",
        description="上市公司公告补充源，默认仅最近 7 天并限量采集。",
        recommended_frequency="daily",
        risk_level="high",
        symbol_scoped=False,
        default_enabled=False,
        text_source=True,
        default_params={"daily_limit": 200},
    ),
    "stock_zh_a_disclosure_report_cninfo": RelayDatasetSpec(
        name="stock_zh_a_disclosure_report_cninfo",
        display_name="巨潮公告",
        api_name="stock_zh_a_disclosure_report_cninfo",
        storage_dataset="announcements",
        date_col="ann_date",
        category="relay_text",
        description="巨潮公告补充源，必须带日期或标的过滤，默认不做全量回灌。",
        recommended_frequency="manual",
        risk_level="high",
        default_enabled=False,
        text_source=True,
        default_params={"daily_limit": 200},
    ),
    "stock_research_report_em": RelayDatasetSpec(
        name="stock_research_report_em",
        display_name="东方财富研报",
        api_name="stock_research_report_em",
        storage_dataset="research_reports",
        date_col="report_date",
        category="relay_text",
        description="研报标题和链接补充源，先用于查询回溯，不直接进入因子。",
        recommended_frequency="manual",
        risk_level="high",
        symbol_scoped=True,
        default_enabled=False,
        text_source=True,
        default_params={"daily_limit": 200},
    ),
    "news_cctv": RelayDatasetSpec(
        name="news_cctv",
        display_name="央视新闻",
        api_name="news_cctv",
        storage_dataset="market_news",
        date_col="publish_time",
        category="relay_text",
        description="宏观新闻补充源，限量采集并保留来源。",
        recommended_frequency="manual",
        risk_level="high",
        default_enabled=False,
        text_source=True,
        default_params={"daily_limit": 200},
    ),
    "news_economic_baidu": RelayDatasetSpec(
        name="news_economic_baidu",
        display_name="百度财经日历",
        api_name="news_economic_baidu",
        storage_dataset="market_news",
        date_col="publish_time",
        category="relay_text",
        description="经济日历补充源，适合宏观事件查询，不直接进入因子。",
        recommended_frequency="manual",
        risk_level="high",
        default_enabled=False,
        text_source=True,
        default_params={"daily_limit": 200},
    ),
    "major_news": RelayDatasetSpec(
        name="major_news",
        display_name="重大新闻",
        api_name="major_news",
        storage_dataset="market_news",
        date_col="publish_time",
        category="relay_text",
        description="市场重大新闻补充源，噪声较高，默认仅限量查询。",
        recommended_frequency="manual",
        risk_level="high",
        default_enabled=False,
        text_source=True,
        default_params={"daily_limit": 200},
    ),
}
